version: 2
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
    - checkout
    - run:
        name: Get test data
        command: |
          if [[ ! -d ~/data/ds114_test1 ]]; then
            wget -c -O ${HOME}/ds114_test1.tar "https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/57e54a326c613b01d7d3ed90" && \
            mkdir -p ${HOME}/data && tar xf ${HOME}/ds114_test1.tar -C ${HOME}/data
          fi
    - run:
        name: Build Docker image
        command: |
          git describe --tags --always > version
          docker build -t bids/${CIRCLE_PROJECT_REPONAME,,} .
          mkdir -p ${HOME}/docker
          docker save "bids/${CIRCLE_PROJECT_REPONAME,,}" > ~/docker/image.tar
          mkdir -p ${HOME}/outputs
    - persist_to_workspace:
        root: /home/circleci
        paths:
        - data/ds114_test1
        - docker/image.tar


  test:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run:
        name: Build Docker image
        command: |
          docker run -ti --rm --read-only \
            -v /tmp:/tmp \
            -v /var/tmp:/var/tmp \
            -v ${HOME}/data/ds114_test1:/bids_dataset \
            -v ${HOME}/outputs:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} \
            /bids_dataset /outputs participant --participant_label 01
        no_output_timeout: 6h
    - run:
        name: Build Docker image
        command: |
          docker run -ti --rm --read-only -v /tmp:/tmp \
            -v /var/tmp:/var/tmp \
            -v ${HOME}/data/ds114_test1:/bids_dataset \
            -v ${HOME}/outputs:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} \
            /bids_dataset /outputs participant --participant_label 02
        no_output_timeout: 6h
    - run:
        name: Build Docker image
        command: |
          docker run -ti --rm --read-only \
            -v /tmp:/tmp \
            -v /var/tmp:/var/tmp \
            -v ${HOME}/data/ds114_test1:/bids_dataset \
            -v ${HOME}/outputs:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} \
            /bids_dataset /outputs group
        no_output_timeout: 6h


  deploy:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - setup_remote_docker
    - run: docker load -i /tmp/workspace/docker/image.tar
    - push:
        command: |
          if [[ -n "${CIRCLE_TAG}" ]]; then
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASS}
            docker push bids/${CIRCLE_PROJECT_REPONAME,,}:latest
            docker tag bids/${CIRCLE_PROJECT_REPONAME,,} bids/${CIRCLE_PROJECT_REPONAME,,}:${CIRCLE_TAG}
            docker push bids/${CIRCLE_PROJECT_REPONAME,,}:${CIRCLE_TAG}
          fi
workflows:
  version: 2
  build-test-deploy:
    jobs:
    - build
    - test:
        requires:
        - build
    - deploy:
        requires:
        - test
        filters:
          tags:
            only: /.*/

# VS Code Extension Version: 1.5.1
